'use strict';
// console.log(document.querySelector('.message'));

//it is an method thats available on the document object.Here we can select element by selectors same as in css.

// what is DOM

// it is structured representation of html documents.
//DOM allows javascript to access the html elementsn and styles to manipulate them.
// we can able to change text content ,html attributes,and evem css styles.
// we can say that DOM is basically a connection point b/w html documents and javascript code.
//  and DOM is automatically created by browsers as soon as the html pages loads

// And it stored in a tree structure like ,generated by browser on html page loads.
// In this tree each html element is one object.

// DOM is not an part of javascript.Actually DOM is an WEB APIs.WEB APIs are like libraries that we can access from our javascript code.

// basicallu web api`s are libraries that are also written in javascript.
// aside DOM there are more web api`s such as timer ,the fetch api and more.

// document.querySelector('.meaasge').textContent = 'CORRECT NUMBER';
// console.log(document.querySelector('.message'));

// document.querySelector('.number').textContent = 13;
// document.querySelector('.score').textContent = 20;
// document.querySelector('.guess').value = 23;
// console.log(document.querySelector('.guess').value);

const secretNumber = Math.trunc(Math.random() * 20) + 1;

let score = 20;
let highScore = 0;
document.querySelector('.check').addEventListener('click', () => {
  const guess = Number(document.querySelector('.guess').value);
  console.log(guess, typeof guess);

  if (!guess) {
    document.querySelector('.message').textContent = 'No  Number !';
  } else if (guess == secretNumber) {
    document.querySelector('.message').textContent = 'correct number !';
    document.querySelector('.number').textContent = secretNumber;
    document.querySelector('.number').style.width = '30rem';
    document.querySelector('body').style.backgroundColor = 'green';

    if (score > highScore) {
      highScore = score;
      document.querySelector('.highscore').textContent = highScore;
    }
  } else if (guess !== secretNumber) {
    if (score > 1) {
      document.querySelector('.message').textContent =
        guess > secretNumber ? 'Too high !' : 'Too low!';
      score--;
      document.querySelector('.score').textContent = score;
    } else {
      document.querySelector('.message').textContent = 'you lost the game ~!';

      document.querySelector('.score').textContent = 0;
    }
  }
  //   } else if (guess < secretNumber) {
  //     if (score > 1) {
  //       document.querySelector('.message').textContent = 'Too low!';
  //       score--;
  //       document.querySelector('.score').textContent = score;
  //     } else {
  //       document.querySelector('.message').textContent = 'you lost the game ~!';

  //       document.querySelector('.score').textContent = 0;
  //     }
  //   }
});

document.querySelector('.again').addEventListener('click', () => {
  const secretNumber = Math.trunc(Math.random() * 20) + 1;

  score = 20;
  document.querySelector('.message').textContent = 'start guessing !';
  document.querySelector('.score').textContent = score;
  document.querySelector('.number').textContent = '?';
  document.querySelector('.number').style.width = '15rem';
  document.querySelector('body').style.backgroundColor = '#222';
  document.querySelector('.guess').value = '';
});

// when ever we get input from user interfacer it always be an string..

// function is value so we can  pass it into another function.
